#!/usr/bin/env python3
"""genlang.py — RisalDash i18n code generator.

Reads the per-language translation files in lang/*.json and emits a single C++
header (src/lang/RisalLang.gen.h) holding:
  - enum RuiStr  : stable string IDs, derived from lang/en.json key order
  - one PROGMEM string table per language, each guarded by #ifdef RISAL_LANG_XX
    (EN is always emitted: it is the default and the runtime fallback)
  - a RuiLang registry listing only the compiled-in languages

en.json is the single source of truth for the key set. Every other language is
validated against it: a missing key falls back to the EN value with a warning;
pass --strict to make any gap a hard error instead.

Usage:
    python tools/genlang.py [--lang-dir lang] [--out src/lang/RisalLang.gen.h] [--strict]
"""
import argparse
import json
import os
import sys

META = "_meta"


def load_lang(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    meta = data.get(META, {})
    strings = {k: v for k, v in data.items() if k != META}
    return meta, strings


def c_escape(s):
    """Escape a Python str into a C string literal body (UTF-8 preserved)."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)  # UTF-8 bytes pass through; source file is UTF-8
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lang-dir", default="lang")
    ap.add_argument("--out", default="src/lang/RisalLang.gen.h")
    ap.add_argument("--strict", action="store_true")
    args = ap.parse_args()

    en_path = os.path.join(args.lang_dir, "en.json")
    if not os.path.isfile(en_path):
        sys.exit(f"error: {en_path} not found (en.json is the key source of truth)")

    _, en = load_lang(en_path)
    keys = list(en.keys())  # enum order = en.json insertion order

    # Discover languages: en first, then the rest alphabetically.
    files = sorted(f for f in os.listdir(args.lang_dir) if f.endswith(".json"))
    codes = ["en"] + [f[:-5] for f in files if f not in ("en.json",)]

    langs = []  # (code, name, rtl, ordered_values)
    for code in codes:
        meta, strings = load_lang(os.path.join(args.lang_dir, f"{code}.json"))
        values = []
        for k in keys:
            if k in strings:
                values.append(strings[k])
            else:
                msg = f"{code}.json missing key {k}"
                if args.strict:
                    sys.exit(f"error: {msg}")
                print(f"  warning: {msg} -> EN fallback", file=sys.stderr)
                values.append(en[k])
        extra = [k for k in strings if k not in en]
        for k in extra:
            print(f"  warning: {code}.json has unknown key {k} (ignored)", file=sys.stderr)
        langs.append((code, meta.get("name", code), bool(meta.get("rtl", False)), values))

    out = []
    w = out.append
    w("// RisalLang.gen.h — GENERATED by tools/genlang.py. Do not edit by hand.")
    w("// Source: lang/*.json. Re-run the generator to update.")
    w("#pragma once")
    w("#include <Arduino.h>")
    w("")
    w("enum RuiStr : uint8_t {")
    for k in keys:
        w(f"  {k},")
    w("  RUI_STR_COUNT")
    w("};")
    w("")
    w("// EN is always compiled: default language and fallback.")
    for code, name, rtl, values in langs:
        guard = code != "en"
        if guard:
            w(f"#ifdef RISAL_LANG_{code.upper()}")
        up = code.upper()
        for i, v in enumerate(values):
            w(f'static const char RUI_{up}_{i}[] PROGMEM = "{c_escape(v)}";')
        w(f"static const char* const RUI_LANG_{up}[RUI_STR_COUNT] PROGMEM = {{")
        w("  " + ", ".join(f"RUI_{up}_{i}" for i in range(len(values))))
        w("};")
        if guard:
            w("#endif")
        w("")

    w("struct RuiLang { const char* code; const char* name; const char* const* table; bool rtl; };")
    w("static const RuiLang RUI_LANGS[] = {")
    for code, name, rtl, _ in langs:
        guard = code != "en"
        up = code.upper()
        if guard:
            w(f"#ifdef RISAL_LANG_{up}")
        w(f'  {{ "{code}", "{c_escape(name)}", RUI_LANG_{up}, {"true" if rtl else "false"} }},')
        if guard:
            w("#endif")
    w("};")
    w("#define RUI_LANG_COUNT (sizeof(RUI_LANGS) / sizeof(RUI_LANGS[0]))")
    w("")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))

    print(f"genlang: {len(keys)} keys, {len(langs)} languages "
          f"({', '.join(c for c, *_ in langs)}) -> {args.out}")


if __name__ == "__main__":
    main()
