// RisalLang.gen.h — GENERATED by tools/genlang.py. Do not edit by hand.
// Source: lang/*.json. Re-run the generator to update.
#pragma once
#include <Arduino.h>

enum RuiStr : uint8_t {
  RUI_WIFI_SETUP,
  RUI_NETWORKS,
  RUI_PASSWORD,
  RUI_SHOW_PW,
  RUI_CONNECT,
  RUI_CONNECTING,
  RUI_CONNECTED,
  RUI_FAILED,
  RUI_SAVED,
  RUI_RESCAN,
  RUI_SECURED,
  RUI_OPEN,
  RUI_REBOOT,
  RUI_FORGET_WIFI,
  RUI_AP_HINT,
  RUI_LIVE,
  RUI_OFFLINE,
  RUI_RECONNECTING,
  RUI_ON,
  RUI_OFF,
  RUI_SAVE,
  RUI_CANCEL,
  RUI_LOADING,
  RUI_THEME,
  RUI_EFFECTS,
  RUI_LANGUAGE,
  RUI_MENU,
  RUI_STR_COUNT
};

// EN is always compiled: default language and fallback.
static const char RUI_EN_0[] PROGMEM = "Wi-Fi Setup";
static const char RUI_EN_1[] PROGMEM = "Networks";
static const char RUI_EN_2[] PROGMEM = "Password";
static const char RUI_EN_3[] PROGMEM = "Show password";
static const char RUI_EN_4[] PROGMEM = "Connect";
static const char RUI_EN_5[] PROGMEM = "Connecting…";
static const char RUI_EN_6[] PROGMEM = "Connected";
static const char RUI_EN_7[] PROGMEM = "Connection failed";
static const char RUI_EN_8[] PROGMEM = "Saved";
static const char RUI_EN_9[] PROGMEM = "Rescan";
static const char RUI_EN_10[] PROGMEM = "Secured";
static const char RUI_EN_11[] PROGMEM = "Open";
static const char RUI_EN_12[] PROGMEM = "Reboot";
static const char RUI_EN_13[] PROGMEM = "Forget Wi-Fi";
static const char RUI_EN_14[] PROGMEM = "Connect to this device's network to configure it.";
static const char RUI_EN_15[] PROGMEM = "live";
static const char RUI_EN_16[] PROGMEM = "offline";
static const char RUI_EN_17[] PROGMEM = "reconnecting…";
static const char RUI_EN_18[] PROGMEM = "On";
static const char RUI_EN_19[] PROGMEM = "Off";
static const char RUI_EN_20[] PROGMEM = "Save";
static const char RUI_EN_21[] PROGMEM = "Cancel";
static const char RUI_EN_22[] PROGMEM = "Loading…";
static const char RUI_EN_23[] PROGMEM = "Theme";
static const char RUI_EN_24[] PROGMEM = "Effects";
static const char RUI_EN_25[] PROGMEM = "Language";
static const char RUI_EN_26[] PROGMEM = "Menu";
static const char* const RUI_LANG_EN[RUI_STR_COUNT] PROGMEM = {
  RUI_EN_0, RUI_EN_1, RUI_EN_2, RUI_EN_3, RUI_EN_4, RUI_EN_5, RUI_EN_6, RUI_EN_7, RUI_EN_8, RUI_EN_9, RUI_EN_10, RUI_EN_11, RUI_EN_12, RUI_EN_13, RUI_EN_14, RUI_EN_15, RUI_EN_16, RUI_EN_17, RUI_EN_18, RUI_EN_19, RUI_EN_20, RUI_EN_21, RUI_EN_22, RUI_EN_23, RUI_EN_24, RUI_EN_25, RUI_EN_26
};

#ifdef RISAL_LANG_AR
static const char RUI_AR_0[] PROGMEM = "إعداد الواي فاي";
static const char RUI_AR_1[] PROGMEM = "الشبكات";
static const char RUI_AR_2[] PROGMEM = "كلمة المرور";
static const char RUI_AR_3[] PROGMEM = "إظهار كلمة المرور";
static const char RUI_AR_4[] PROGMEM = "اتصال";
static const char RUI_AR_5[] PROGMEM = "جارٍ الاتصال…";
static const char RUI_AR_6[] PROGMEM = "متصل";
static const char RUI_AR_7[] PROGMEM = "فشل الاتصال";
static const char RUI_AR_8[] PROGMEM = "تم الحفظ";
static const char RUI_AR_9[] PROGMEM = "إعادة المسح";
static const char RUI_AR_10[] PROGMEM = "محمية";
static const char RUI_AR_11[] PROGMEM = "مفتوحة";
static const char RUI_AR_12[] PROGMEM = "إعادة التشغيل";
static const char RUI_AR_13[] PROGMEM = "نسيان الشبكة";
static const char RUI_AR_14[] PROGMEM = "اتصل بشبكة هذا الجهاز لإعداده.";
static const char RUI_AR_15[] PROGMEM = "مباشر";
static const char RUI_AR_16[] PROGMEM = "غير متصل";
static const char RUI_AR_17[] PROGMEM = "إعادة الاتصال…";
static const char RUI_AR_18[] PROGMEM = "تشغيل";
static const char RUI_AR_19[] PROGMEM = "إيقاف";
static const char RUI_AR_20[] PROGMEM = "حفظ";
static const char RUI_AR_21[] PROGMEM = "إلغاء";
static const char RUI_AR_22[] PROGMEM = "جارٍ التحميل…";
static const char RUI_AR_23[] PROGMEM = "السمة";
static const char RUI_AR_24[] PROGMEM = "التأثيرات";
static const char RUI_AR_25[] PROGMEM = "اللغة";
static const char RUI_AR_26[] PROGMEM = "القائمة";
static const char* const RUI_LANG_AR[RUI_STR_COUNT] PROGMEM = {
  RUI_AR_0, RUI_AR_1, RUI_AR_2, RUI_AR_3, RUI_AR_4, RUI_AR_5, RUI_AR_6, RUI_AR_7, RUI_AR_8, RUI_AR_9, RUI_AR_10, RUI_AR_11, RUI_AR_12, RUI_AR_13, RUI_AR_14, RUI_AR_15, RUI_AR_16, RUI_AR_17, RUI_AR_18, RUI_AR_19, RUI_AR_20, RUI_AR_21, RUI_AR_22, RUI_AR_23, RUI_AR_24, RUI_AR_25, RUI_AR_26
};
#endif

#ifdef RISAL_LANG_RU
static const char RUI_RU_0[] PROGMEM = "Настройка Wi-Fi";
static const char RUI_RU_1[] PROGMEM = "Сети";
static const char RUI_RU_2[] PROGMEM = "Пароль";
static const char RUI_RU_3[] PROGMEM = "Показать пароль";
static const char RUI_RU_4[] PROGMEM = "Подключить";
static const char RUI_RU_5[] PROGMEM = "Подключение…";
static const char RUI_RU_6[] PROGMEM = "Подключено";
static const char RUI_RU_7[] PROGMEM = "Ошибка подключения";
static const char RUI_RU_8[] PROGMEM = "Сохранено";
static const char RUI_RU_9[] PROGMEM = "Сканировать снова";
static const char RUI_RU_10[] PROGMEM = "Защищённая";
static const char RUI_RU_11[] PROGMEM = "Открытая";
static const char RUI_RU_12[] PROGMEM = "Перезагрузка";
static const char RUI_RU_13[] PROGMEM = "Забыть сеть";
static const char RUI_RU_14[] PROGMEM = "Подключитесь к сети устройства, чтобы настроить его.";
static const char RUI_RU_15[] PROGMEM = "онлайн";
static const char RUI_RU_16[] PROGMEM = "оффлайн";
static const char RUI_RU_17[] PROGMEM = "переподключение…";
static const char RUI_RU_18[] PROGMEM = "Вкл";
static const char RUI_RU_19[] PROGMEM = "Выкл";
static const char RUI_RU_20[] PROGMEM = "Сохранить";
static const char RUI_RU_21[] PROGMEM = "Отмена";
static const char RUI_RU_22[] PROGMEM = "Загрузка…";
static const char RUI_RU_23[] PROGMEM = "Тема";
static const char RUI_RU_24[] PROGMEM = "Эффекты";
static const char RUI_RU_25[] PROGMEM = "Язык";
static const char RUI_RU_26[] PROGMEM = "Меню";
static const char* const RUI_LANG_RU[RUI_STR_COUNT] PROGMEM = {
  RUI_RU_0, RUI_RU_1, RUI_RU_2, RUI_RU_3, RUI_RU_4, RUI_RU_5, RUI_RU_6, RUI_RU_7, RUI_RU_8, RUI_RU_9, RUI_RU_10, RUI_RU_11, RUI_RU_12, RUI_RU_13, RUI_RU_14, RUI_RU_15, RUI_RU_16, RUI_RU_17, RUI_RU_18, RUI_RU_19, RUI_RU_20, RUI_RU_21, RUI_RU_22, RUI_RU_23, RUI_RU_24, RUI_RU_25, RUI_RU_26
};
#endif

struct RuiLang { const char* code; const char* name; const char* const* table; bool rtl; };
static const RuiLang RUI_LANGS[] = {
  { "en", "English", RUI_LANG_EN, false },
#ifdef RISAL_LANG_AR
  { "ar", "العربية", RUI_LANG_AR, true },
#endif
#ifdef RISAL_LANG_RU
  { "ru", "Русский", RUI_LANG_RU, false },
#endif
};
#define RUI_LANG_COUNT (sizeof(RUI_LANGS) / sizeof(RUI_LANGS[0]))
